menuTitle: Enter authentication credentials
weight: 600
step: 7
layout: single-journey
cta:
  type: continue
keywords:
- Grafana Cloud
- Prometheus
- Data source
- Authentication
side_journeys:
  title: More to explore (optional)
  heading: 'At this point in your journey, you can explore the following paths:'
  items:
  - title: Authentication
    link: /docs/grafana-cloud/connect-externally-hosted/data-sources/prometheus/configure-prometheus-data-source/#authentication-section
  - title: Advanced settings
    link: /docs/grafana-cloud/connect-externally-hosted/data-sources/prometheus/configure-prometheus-data-source/#advanced-settings
description: Learn how to configure basic authentication to the Prometheus data source connection
