menuTitle: Enter data source URL
weight: 500
step: 6
layout: single-journey
cta:
  type: continue
keywords:
- Prometheus
- Configuration
- URL
side_journeys:
  title: More to explore (optional)
  heading: 'At this point in your journey, you can explore the following paths:'
  items:
  - title: Create a private connection to a data source
    link: /docs/learning-paths/private-data-source-connect
