menuTitle: Connect to a Prometheus data source
weight: 300
journey:
  group: data-availability
  skill: Beginner
  source: Docs & blog posts
  logo:
    src: /static/img/menu/prometheus.svg
step: 1
layout: single-journey
cascade:
  layout: single-journey
cta:
  type: start
  title: Are you ready?
  cta_text: Let's go!
related_journeys:
  title: Related paths
  heading: Consider taking the following journeys before you start this journey.
  items:
  - title: Create a private connection to a data source
    link: /docs/learning-paths/private-data-source-connect/
