menuTitle: Add data source
weight: 400
step: 5
layout: single-journey
cta:
  type: continue
keywords:
- Prometheus
- Data source
- Add
- Configure
side_journeys:
  title: More to explore (optional)
  heading: 'At this point in your journey, you can explore the following paths:'
  items:
  - title: Adding data sources to Grafana (video)
    link: https://www.youtube.com/watch?v=cqHO0oYW6Ic&list=PLDGkOdUX1Ujo27m6qiTPPCpFHVfyKq9jT&index=8
  - title: Data source plugins for Grafana
    link: https://grafana.com/grafana/plugins/data-source-plugins/
description: Learn how to navigate Grafana Cloud and add the Prometheus data source
