menuTitle: Verify metrics
weight: 300
step: 4
layout: single-journey
cta:
  type: success
keywords:
- Prometheus
- Grafana Cloud
- Metrics
side_journeys:
  title: More to explore (optional)
  heading: 'At this point in your journey, you can explore the following paths:'
  items:
  - title: Send data from a Prometheus instance
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-a-prometheus-instance
  - title: Send data from multiple Prometheus instances
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-multiple-prometheus-instances
  - title: Send data from multiple high-availability Prometheus instances
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-multiple-high-availability-prometheus-instances
