menuTitle: When to connect
weight: 200
step: 3
layout: single-journey
cta:
  type: continue
keywords:
- Grafana Labs
- observability
- monitoring
- Prometheus
side_journeys:
  title: More to explore (optional)
  heading: 'At this point in your journey, you can explore the following paths:'
  items:
  - title: What is Prometheus?
    link: /docs/grafana-cloud/introduction/what-is-observability/prometheus/
  - title: Send data from a Prometheus instance
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-a-prometheus-instance
  - title: Send data from multiple Prometheus instances
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-multiple-prometheus-instances
  - title: Send data from multiple high-availability Prometheus instances
    link: /docs/grafana-cloud/send-data/metrics/metrics-prometheus/#send-data-from-multiple-high-availability-prometheus-instances
description: Learn about observability and how it can help you solve real-world problems
