name: Deploy PR preview

permissions: {}

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - closed

jobs:
  deploy-pr-preview:
    uses: grafana/writers-toolkit/.github/workflows/deploy-preview.yml@4dbecae7443c69b3e5fdfeeac7037a339cb82e4c # main
    if: >-
      !github.event.pull_request.head.repo.fork &&
      (contains(github.event.pull_request.labels.*.name, 'deploy-preview') ||
      github.event.action == 'closed')
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      statuses: write
    with:
      branch: ${{ github.head_ref }}
      build_script: build-interactive-tutorials
      event_number: ${{ github.event.number }}
      image: grafana/docs-base:latest
      repo: interactive-tutorials
      sha: ${{ github.event.pull_request.head.sha }}
      sources: |
        [{
          "index_file": null,
          "relative_prefix": "/docs/learning-paths/",
          "repo": "interactive-tutorials",
          "source_directory": ".",
          "website_directory": "content/docs/learning-paths"
        }]
      title: ${{ github.event.pull_request.title }}
